###########################################################################
#                                                                         #
# MAKE FILE FOR address.EXE                                               #
#                                                                         #
# NOTES:                                                                  #
#                                                                         #
#  To enable the C Set/2 memory management debugging code, uncomment the  #
#  DEBUGALLOC macro. The debugging info will be sent to address.DBG.      #
#                                                                         #
# HISTORY:                                                                #
#                                                                         #
#  10-09-92 - created                                                     #
#                                                                         #
#  Rick Fishman                                                           #
#  Code Blazers, Inc.                                                     #
#  4113 Apricot                                                           #
#  Irvine, CA. 92720                                                      #
#  CIS ID: 72251,750                                                      #
#                                                                         #
###########################################################################

#DEBUGALLOC=-D__DEBUG_ALLOC__

BASE=address

CFLAGS=/Q+ /Ss /W3 /Kbcepr /Gm+ /Gd- /Ti+ /O- $(DEBUGALLOC) /C
LFLAGS=/NOI /NOE /MAP /DE /NOL /A:16 /EXEPACK /BASE:65536

.SUFFIXES: .c

.c.obj:
    icc $(CFLAGS) $*.c

OFILES=$(BASE).obj create.obj populate.obj common.obj
LFILES=$(OFILES:.obj=)

$(BASE).exe: $(OFILES) $(BASE).res $(BASE).def
    link386 $(LFLAGS) $(LFILES),,, os2386, $*
    rc $*.res $@

$(BASE).res: $*.rc
    rc -r $*

$(BASE).obj:  $*.c $(BASE).h
create.obj:   $*.c $(BASE).h
common.obj:   $*.c $(BASE).h
populate.obj: $*.c $(BASE).h

###########################################################################
#                       E N D   O F   S O U R C E                         #
###########################################################################
